/**
 * Generated db/migrations/0002_rbac_seed.sql (the first permission matrix) from
 * src/modules/rbac/permissions.ts. 0002 is applied and frozen: add new permissions
 * in a new migration. test/rbac.int.test.ts checks the migrated database matches
 * permissions.ts.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { PERMISSIONS, ROLE_INFO, ROLE_PERMISSIONS, ROLES } from "../src/modules/rbac/permissions.ts";

export function rbacSeedSql(): string {
  const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
  const lines = [
    "-- GENERATED by scripts/rbac-seed-sql.ts from src/modules/rbac/permissions.ts. Do not edit by hand.",
    "delete from platform.role_permissions;",
    "insert into platform.roles (id, name, description, rank) values",
    ROLES.map((r) => `  (${q(r)}, ${q(ROLE_INFO[r].name)}, ${q(ROLE_INFO[r].description)}, ${ROLE_INFO[r].rank})`).join(",\n") +
      "\non conflict (id) do update set name = excluded.name, description = excluded.description, rank = excluded.rank;",
    "insert into platform.permissions (id, description) values",
    Object.entries(PERMISSIONS).map(([id, d]) => `  (${q(id)}, ${q(d)})`).join(",\n") +
      "\non conflict (id) do update set description = excluded.description;",
    "insert into platform.role_permissions (role_id, permission_id) values",
    ROLES.flatMap((r) => ROLE_PERMISSIONS[r].map((p) => `  (${q(r)}, ${q(p)})`)).join(",\n") + ";",
    "",
  ];
  return lines.join("\n");
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  const out = path.join(import.meta.dirname, "../db/migrations/0002_rbac_seed.sql");
  writeFileSync(out, rbacSeedSql());
  console.log(`wrote ${out}`);
}
