import Link from "next/link";
import { approveAction, planEditAction, publishAction, type PlanEditOp } from "@/app/actions/implementation";
import { ActionForm } from "@/components/ActionForm";
import { CodeTabs } from "@/components/CodeTabs";
import { MODEL_LABELS, type BusinessModel } from "@/modules/implementation/catalog/models";
import { generateSnippets, SDK_AVAILABILITY } from "@/modules/implementation/codegen";
import { EVENT_PROPERTY_TYPES, EVENT_SOURCES, PRIORITIES, USER_PROPERTY_SOURCES, USER_PROPERTY_TYPES } from "@/modules/implementation/plan-input";
import { getPlanVersion, listVersions } from "@/modules/implementation/service";
import { can } from "@/modules/rbac/authorize";
import { publicBaseUrl } from "@/server/env";
import { loadApp } from "@/server/session";

export const metadata = { title: "Tracking plan" };

const STATUS_STYLE: Record<string, string> = {
  draft: "border-warn/50 text-warn",
  approved: "border-accent/50 text-accent-ink",
  published: "border-accent bg-accent text-paper",
  archived: "border-line text-ink-3",
};
const PRIORITY_STYLE: Record<string, string> = { critical: "text-alert", high: "text-ink", medium: "text-ink-2", low: "text-ink-3" };
const SOURCE_LABEL: Record<string, string> = { mobile_sdk: "App (SDK)", backend: "Backend", both: "App + backend", automatic: "Automatic" };

export default async function PlanPage(props: PageProps<"/o/[org]/apps/[app]/settings/dev-ops/implementation/plan">) {
  const { org, app } = await props.params;
  const sp = await props.searchParams;
  const { ctx, app: a } = await loadApp(org, app);
  const versions = await listVersions(ctx, a.id);
  const plan = await getPlanVersion(ctx, a.id, typeof sp.version === "string" ? sp.version : undefined);
  const base = `/o/${org}/apps/${app}`;

  if (!plan) {
    return (
      <div className="card">
        <h1 className="h1">Tracking plan</h1>
        <p className="mt-2 text-ink-2">No plan yet. Answer the questions and we&apos;ll generate one.</p>
        <Link href={`${base}/settings/dev-ops/implementation/questions`} className="btn mt-4">Go to questions</Link>
      </div>
    );
  }

  const v = plan.version;
  const isDraft = v.status === "draft";
  const mayEdit = can(ctx.role, "implementation.edit");
  // Edits always land on the working draft. Without one, the newest approved / published version is copied into a new draft.
  const draft = versions.find((x) => x.status === "draft");
  const draftBase = versions.find((x) => x.status !== "archived") ?? versions[0];
  const canEdit = mayEdit && (isDraft || (!draft && v.id === draftBase?.id));
  const nextVersion = Math.max(...versions.map((x) => x.version)) + 1;
  const edit = (op: PlanEditOp) => planEditAction.bind(null, org, app, a.id, op);
  const canApprove = can(ctx.role, "implementation.approve");
  const baseUrl = publicBaseUrl();
  const counts = {
    total: plan.events.length,
    required: plan.events.filter((e) => e.required).length,
    backend: plan.events.filter((e) => e.source === "backend").length,
  };
  const roles = (name: string) =>
    [name === v.activation_event && "activation", name === v.north_star_event && "north star", name === v.summary.revenue_event && "revenue"].filter(Boolean) as string[];

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="h1">Tracking plan</h1>
          <p className="mt-1 text-ink-2">
            Version {v.version} <span className={`pill ms-1 ${STATUS_STYLE[v.status]}`}>{v.status}</span>
            <span className="ms-2 text-sm text-ink-3">generated by {v.generator} on {new Date(v.created_at).toLocaleDateString("en-GB")}</span>
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {isDraft && canApprove && <ActionForm action={approveAction.bind(null, org, app, a.id, v.id)} submitLabel="Approve plan" className="contents" />}
          {v.status === "approved" && canApprove && (
            <ActionForm action={publishAction.bind(null, org, app, a.id, v.id)} submitLabel="Publish plan" className="contents" confirm="Publish this version? Incoming events will be validated against it." />
          )}
          <Link href={`${base}/settings/dev-ops/implementation/questions`} className="btn-secondary">Edit answers</Link>
          {versions.length > 1 && <Link href={`${base}/settings/dev-ops/implementation/plan/diff?to=${v.id}`} className="btn-secondary">Compare versions</Link>}
          <a href={`${base}/settings/dev-ops/implementation/plan/export?version=${v.id}&format=json`} className="btn-secondary" download>Export JSON</a>
          <a href={`${base}/settings/dev-ops/implementation/plan/export?version=${v.id}&format=csv`} className="btn-secondary" download>Export CSV</a>
        </div>
      </div>

      {canEdit && !isDraft && (
        <p className="rounded-lg border border-line bg-paper-2 px-3 py-2 text-sm text-ink-2">
          Version {v.version} is {v.status} and can&apos;t change. Editing it creates draft v{nextVersion} from it; publish that draft when it&apos;s ready.
        </p>
      )}
      {mayEdit && !canEdit && draft && draft.id !== v.id && (
        <p className="rounded-lg border border-line bg-paper-2 px-3 py-2 text-sm text-ink-2">
          Changes go to the working draft. <Link href={`?version=${draft.id}`} className="underline">Edit draft v{draft.version}</Link>
        </p>
      )}

      {versions.length > 1 && (
        <div className="flex flex-wrap gap-2 text-sm">
          {versions.map((x) => (
            <Link key={x.id} href={`?version=${x.id}`} className={`rounded-full border px-3 py-1 ${x.id === v.id ? "border-ink bg-ink text-paper" : "border-line text-ink-2"}`}>
              v{x.version} · {x.status}
            </Link>
          ))}
        </div>
      )}

      <div className="grid gap-4 md:grid-cols-4">
        <Stat label="Business model" value={MODEL_LABELS[(v.business_model ?? "other") as BusinessModel]} sub={`${v.summary.classification?.confidence ?? ""} confidence`} />
        <Stat label="Activation" value={v.activation_event ?? "–"} mono />
        <Stat label="North star" value={v.north_star_event ?? "–"} mono />
        <Stat label="Revenue event" value={v.summary.revenue_event ?? "none"} mono />
      </div>

      {(v.summary.warnings?.length ?? 0) > 0 && (
        <ul className="space-y-2">
          {v.summary.warnings.map((w) => <li key={w} className="rounded-lg border border-warn/40 bg-warn-soft px-3 py-2 text-sm">{w}</li>)}
        </ul>
      )}
      {(v.summary.journey_matches?.length ?? 0) > 0 && (
        <div className="card text-sm">
          <p className="font-mono text-xs uppercase tracking-wide text-ink-3">From your journey description</p>
          <ul className="mt-2 flex flex-wrap gap-2">
            {v.summary.journey_matches.map((m) => (
              <li key={m.phrase} className="rounded-md bg-paper-2 px-2 py-1">“{m.phrase}” → <span className="font-mono">{m.events.join(", ")}</span></li>
            ))}
          </ul>
        </div>
      )}

      <section>
        <h2 className="h2">Events <span className="text-sm font-normal text-ink-3">{counts.total} events · {counts.required} required · {counts.backend} from your backend</span></h2>
        <p className="mt-1 text-sm text-ink-3">Click an event for its properties, why it&apos;s recommended, and code for every platform.</p>
        <div className="mt-3 space-y-2">
          {plan.events.map((e) => {
            const snippets = generateSnippets(
              { event_name: e.event_name, source: e.source, properties: e.properties.map((p) => ({ name: p.name, type: p.type, required: p.required, example: p.example ?? undefined })) },
              { currency: a.default_currency, baseUrl },
            );
            const r = roles(e.event_name);
            return (
              <details key={e.id} className="card group p-0">
                <summary className="flex cursor-pointer list-none flex-wrap items-center gap-x-4 gap-y-1 px-4 py-3">
                  <span className="font-mono text-sm font-medium">{e.event_name}</span>
                  <span className={`text-xs uppercase ${PRIORITY_STYLE[e.priority]}`}>{e.priority}</span>
                  <span className="text-xs text-ink-3">{SOURCE_LABEL[e.source]}</span>
                  {e.required && <span className="pill border-ink/30">required</span>}
                  {r.map((x) => <span key={x} className="pill border-accent/50 text-accent-ink">{x}</span>)}
                  <span className="ms-auto flex gap-1 text-[11px] text-ink-3">
                    {e.conversion_relevance && <span title="Conversion">CONV</span>}
                    {e.revenue_relevance && <span title="Revenue">REV</span>}
                    {e.attribution_relevance && <span title="Attribution">ATTR</span>}
                    {e.automation_relevance && <span title="Automation">AUTO</span>}
                  </span>
                </summary>
                <div className="space-y-4 border-t border-line px-4 py-4 text-sm">
                  <p><strong>{e.display_name}.</strong> {e.description}</p>
                  <p><span className="text-ink-3">Fires when:</span> {e.trigger}</p>
                  <p><span className="text-ink-3">Why:</span> {e.reason}</p>
                  <p><span className="text-ink-3">Platforms:</span> {e.platforms.join(", ") || "–"}</p>
                  {e.properties.length > 0 ? (
                    <div className="overflow-x-auto">
                      <table className="table">
                        <thead><tr><th>Property</th><th>Type</th><th>Required</th><th>Description</th><th>Example</th>{canEdit && <th />}</tr></thead>
                        <tbody>
                          {e.properties.map((p) => (
                            <tr key={p.name}>
                              <td className="font-mono">{p.name}</td>
                              <td className="font-mono text-ink-2">{p.type}</td>
                              <td>{p.required ? "yes" : ""}</td>
                              <td className="text-ink-2">{p.description}{p.allowed_values ? <span className="block font-mono text-xs text-ink-3">{p.allowed_values.join(" | ")}</span> : null}</td>
                              <td className="font-mono text-xs">{p.example === null || p.example === undefined ? "" : JSON.stringify(p.example)}</td>
                              {canEdit && (
                                <td><ActionForm action={edit({ kind: "remove_property", event: e.event_name, property: p.name })} submitLabel="Remove" buttonClass="btn-danger" className="contents" confirm={`Remove ${p.name} from ${e.event_name}?`} /></td>
                              )}
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  ) : (
                    <p className="text-ink-3">No properties.</p>
                  )}
                  <CodeTabs
                    preferred={e.source === "backend" ? "backend" : "react_native"}
                    tabs={(Object.keys(snippets) as (keyof typeof snippets)[]).map((k) => ({ key: k, label: SDK_AVAILABILITY[k].label, code: snippets[k], note: k === "backend" ? undefined : SDK_AVAILABILITY[k].note }))}
                  />
                  {canEdit && (
                    <div className="space-y-3 border-t border-line pt-3">
                      <div className="flex flex-wrap gap-2">
                        <ActionForm action={edit({ kind: "event_required", event: e.event_name, required: !e.required })} submitLabel={e.required ? "Mark optional" : "Mark required"} buttonClass="btn-secondary" className="contents" />
                        <ActionForm action={edit({ kind: "remove_event", event: e.event_name })} submitLabel="Remove from plan" buttonClass="btn-danger" className="contents" confirm={`Remove ${e.event_name} from the draft?`} />
                      </div>
                      <PropertyForm action={edit({ kind: "set_property", event: e.event_name })} />
                    </div>
                  )}
                </div>
              </details>
            );
          })}
        </div>
      </section>

      {canEdit && (
        <section className="card">
          <h2 className="h2">Add an event</h2>
          <p className="mb-3 text-sm text-ink-3">snake_case, object then past-tense action (<span className="font-mono">gift_card_redeemed</span>). A standard name such as <span className="font-mono">refund_completed</span> starts from the library definition and properties.</p>
          <ActionForm action={edit({ kind: "add_event" })} submitLabel="Add event" buttonClass="btn-secondary" className="grid gap-3 md:grid-cols-3">
            <div><label className="label" htmlFor="ev-name">Event name</label><input className="input font-mono" id="ev-name" name="event_name" required pattern="[a-z][a-z0-9_]{1,63}" placeholder="gift_card_redeemed" /></div>
            <div><label className="label" htmlFor="ev-display">Display name</label><input className="input" id="ev-display" name="display_name" maxLength={100} placeholder="Gift Card Redeemed" /></div>
            <div><label className="label" htmlFor="ev-category">Category</label><input className="input" id="ev-category" name="category" maxLength={40} placeholder="custom" /></div>
            <div className="md:col-span-2"><label className="label" htmlFor="ev-desc">Description</label><input className="input" id="ev-desc" name="description" maxLength={1000} /></div>
            <div><label className="label" htmlFor="ev-trigger">Fires when</label><input className="input" id="ev-trigger" name="trigger" maxLength={500} /></div>
            <div><label className="label" htmlFor="ev-source">Source</label><select className="input" id="ev-source" name="source" defaultValue="mobile_sdk">{EVENT_SOURCES.map((x) => <option key={x} value={x}>{SOURCE_LABEL[x]}</option>)}</select></div>
            <div><label className="label" htmlFor="ev-priority">Priority</label><select className="input" id="ev-priority" name="priority" defaultValue="medium">{PRIORITIES.map((x) => <option key={x}>{x}</option>)}</select></div>
            <label className="flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" name="required" /> Required</label>
          </ActionForm>
        </section>
      )}

      <section className="grid gap-6 lg:grid-cols-2">
        <div className="card overflow-x-auto">
          <h2 className="h2">User properties</h2>
          <p className="mb-3 text-sm text-ink-3">Facts about the person, set with identify / setUserProperties. Actions belong in event properties.</p>
          <table className="table">
            <thead><tr><th>Name</th><th>Type</th><th>Source</th><th>Why</th>{canEdit && <th />}</tr></thead>
            <tbody>
              {plan.userProperties.map((u) => (
                <tr key={u.name}>
                  <td className="font-mono">{u.name}</td><td className="font-mono text-ink-2">{u.type}</td><td className="text-ink-2">{u.source}</td><td className="text-ink-2">{u.description} {u.reason}</td>
                  {canEdit && <td><ActionForm action={edit({ kind: "remove_user_property", name: u.name })} submitLabel="Remove" buttonClass="btn-danger" className="contents" confirm={`Remove user property ${u.name}?`} /></td>}
                </tr>
              ))}
            </tbody>
          </table>
          {canEdit && (
            <ActionForm action={edit({ kind: "set_user_property" })} submitLabel="Save user property" buttonClass="btn-secondary" className="mt-4 grid gap-2 border-t border-line pt-3 sm:grid-cols-2">
              <div><label className="label" htmlFor="up-name">Name</label><input className="input font-mono" id="up-name" name="name" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="loyalty_tier" /></div>
              <div><label className="label" htmlFor="up-type">Type</label><select className="input" id="up-type" name="type">{USER_PROPERTY_TYPES.map((x) => <option key={x}>{x}</option>)}</select></div>
              <div><label className="label" htmlFor="up-desc">Description</label><input className="input" id="up-desc" name="description" maxLength={500} /></div>
              <div><label className="label" htmlFor="up-source">Source</label><select className="input" id="up-source" name="source" defaultValue="mobile_sdk">{USER_PROPERTY_SOURCES.map((x) => <option key={x}>{x}</option>)}</select></div>
              <p className="text-xs text-ink-3 sm:col-span-2">Saving an existing name replaces it.</p>
            </ActionForm>
          )}
        </div>
        <div className="card overflow-x-auto">
          <h2 className="h2">Attribution</h2>
          <p className="mb-3 text-sm text-ink-3">Parameters each channel must carry so installs and conversions keep their source.</p>
          {plan.attributionRules.length === 0 ? <p className="text-sm text-ink-3">No channels selected.</p> : (
            <table className="table">
              <thead><tr><th>Channel</th><th>Click id</th><th>Notes</th></tr></thead>
              <tbody>
                {plan.attributionRules.map((r) => (
                  <tr key={r.channel}><td className="font-medium">{r.channel}</td><td className="font-mono text-xs">{r.click_id_param ?? "–"}</td><td className="text-ink-2">{r.notes}</td></tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </section>
    </div>
  );
}

function PropertyForm({ action }: { action: Parameters<typeof ActionForm>[0]["action"] }) {
  return (
    <ActionForm action={action} submitLabel="Save property" buttonClass="btn-secondary" className="flex flex-wrap items-end gap-2">
      <label className="text-xs text-ink-2">Property<input className="input mt-1 min-h-9 w-40 font-mono text-sm" name="name" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="gift_card_id" /></label>
      <label className="text-xs text-ink-2">Type<select className="input mt-1 min-h-9 w-auto text-sm" name="type">{EVENT_PROPERTY_TYPES.map((x) => <option key={x}>{x}</option>)}</select></label>
      <label className="min-w-40 flex-1 text-xs text-ink-2">Description<input className="input mt-1 min-h-9 text-sm" name="description" maxLength={500} /></label>
      <label className="text-xs text-ink-2">Allowed values<input className="input mt-1 min-h-9 w-40 text-sm" name="allowed_values" placeholder="a | b | c" /></label>
      <label className="flex min-h-9 items-center gap-2 text-sm"><input type="checkbox" name="required" /> Required</label>
      <span className="w-full text-xs text-ink-3">Saving an existing property name replaces it.</span>
    </ActionForm>
  );
}

function Stat({ label, value, sub, mono }: { label: string; value: string; sub?: string; mono?: boolean }) {
  return (
    <div className="card">
      <p className="font-mono text-[11px] uppercase tracking-wide text-ink-3">{label}</p>
      <p className={`mt-1 truncate text-lg font-bold ${mono ? "font-mono text-base" : ""}`}>{value}</p>
      {sub && <p className="text-xs text-ink-3">{sub}</p>}
    </div>
  );
}
